<?php

namespace SiteBundle\Repository;

/**
 * BlockSortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockSortRepository extends \Doctrine\ORM\EntityRepository
{
}
