<?php

namespace SiteBundle\Repository;

/**
 * BlocksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTopSliderBlocks($count) {
        $qb = $this->createQueryBuilder('b');
        $qb->join('b.blockSort', 'bs')
            ->where($qb->expr()->eq('bs.code', '\'top_slider_main\''))
            ->andWhere($qb->expr()->isNotNull('bs.sort'))
            ->orderBy('bs.sort', 'asc')->setMaxResults($count);

        $result = $qb->getQuery()->getResult();

        return $result;
    }

    public function getMidGridBlocks($count) {
        $qb = $this->createQueryBuilder('b');
        $qb->join('b.blockSort', 'bs')
            ->where($qb->expr()->eq('bs.code', '\'middle_blocks_main\''))
            ->andWhere($qb->expr()->isNotNull('bs.sort'))
            ->orderBy('bs.sort', 'asc')->setMaxResults($count);

        $result = $qb->getQuery()->getResult();

        return $result;
    }

    public function getSocialBlocks($count) {
        $qb = $this->createQueryBuilder('b');
        $qb->join('b.blockSort', 'bs')
            ->where($qb->expr()->eq('bs.code', '\'social_block\''))
            ->andWhere($qb->expr()->isNotNull('bs.sort'))
            ->orderBy('bs.sort', 'asc')->setMaxResults($count);

        $result = $qb->getQuery()->getResult();

        return $result;
    }

    public function getTabBlocks($count) {
        $qb = $this->createQueryBuilder('b');
        $qb->join('b.blockSort', 'bs')
            ->where($qb->expr()->eq('bs.code', '\'tab_main\''))
            ->andWhere($qb->expr()->isNotNull('bs.sort'))
            ->orderBy('bs.sort', 'asc')->setMaxResults($count);

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
