<?php

namespace SiteBundle\Repository;

/**
 * ContactsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getContactsIndexedByCode() {
        $qb = $this->createQueryBuilder('c');
        $qb->indexBy('c', 'c.code');

        $result = $qb->getQuery()->getResult();

        return $result;
    }

    public function getSocialBlocks($count) {
        $qb = $this->createQueryBuilder('b');
        $qb->join('b.blockSort', 'bs')
            ->where($qb->expr()->eq('bs.code', '\'social_block\''))
            ->andWhere($qb->expr()->isNotNull('bs.sort'))
            ->orderBy('bs.sort', 'asc')->setMaxResults($count);

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
