<?php

namespace SiteBundle\Repository;

/**
 * FeedbackResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackResultRepository extends \Doctrine\ORM\EntityRepository
{
}
