<?php

namespace SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
//    public function getTopBannerArticles() {
//        $qb = $this->createQueryBuilder('u');
//        $qb->where($qb->expr()->isNotNull('u.topBannerSort'))->orderBy('u.topBannerSort', 'asc');
//
//        return $qb->getQuery()
//            ->getResult();
//    }
//
//    public function getRecommendedArticles() {
//        $qb = $this->createQueryBuilder('u');
//        $qb->where($qb->expr()->isNotNull('u.recommendedSort'))->orderBy('u.recommendedSort', 'asc');
//
//        return $qb->getQuery()
//            ->getResult();
//    }
//
//    public function getTopArticles() {
//        $qb = $this->createQueryBuilder('u');
//        $qb->where($qb->expr()->isNotNull('u.topSort'))->orderBy('u.topSort', 'asc');
//
//        return $qb->getQuery()
//            ->getResult();
//    }
//
//    public function getMostViewArticles($maxResults = 10) {
//        $qb = $this->createQueryBuilder('u');
//        $qb->where($qb->expr()->isNotNull('u.viewCount'))->orderBy('u.viewCount', 'desc')->setMaxResults(intval($maxResults));
//
//        return $qb->getQuery()
//            ->getResult();
//    }
//
//    public function getLatestCommentedArticles($maxResults) {
//        $qb = $this->createQueryBuilder('u')->join('u.replies', 'replies');
//        $qb->where($qb->expr()->isNotNull('u.viewCount'))
//            ->addSelect('count(replies) AS HIDDEN comment_count')
//            //->having($qb->expr()->gt('comment_count', 1))
//            ->orderBy('replies.dateCreated', 'desc')
//            ->groupBy('u.id')
//            ->setMaxResults(intval($maxResults));
//
//        return $qb->getQuery()
//            ->getResult();
//    }
}
