<?php

namespace SiteBundle\Repository;

/**
 * ProductSpecRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductSpecRepository extends \Doctrine\ORM\EntityRepository
{
}
