<?php

namespace SiteBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTagOfTheDay() {
        $qb = $this->createQueryBuilder('u');
        $qb->where('u.tagOfTheDay = 1')->setMaxResults(1);
        fileDump($qb->getQuery()->getSQL(), true);
        return $qb->getQuery()
            ->getResult();
    }
}
