imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@SiteBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    serializer: true
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    globals:
        en: false
        company_footer: false
    debug:            true
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        entity_managers:
            default:
                mappings:
                    SiteBundle: ~
                    SonataUserBundle: ~
                    FOSUserBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    # host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    bundles:        [ SiteBundle ]
    filters:
        cssrewrite: ~

# ...


sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]
        # ...
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes


        # Default configuration for extension with alias: "sonata_admin"
sonata_admin:
    security:
        handler: sonata.admin.security.handler.role
    options:
        html5_validate:       true

        # Auto order groups and admins by label or id
        sort_admins:          false
        confirm_exit:         true
        use_select2:          true
        use_icheck:           true
        use_bootlint:         false
        use_stickyforms:      true
        pager_links:          10
        form_type:            standard
        dropdown_number_groups_per_colums:  10

    assets:
        stylesheets:

            # Defaults:
            - bundles/sonatacore/vendor/bootstrap/dist/css/bootstrap.min.css
            - bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
            - bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/AdminLTE.min.css
            - bundles/sonataadmin/vendor/admin-lte/dist/css/skins/skin-black.min.css
            - bundles/sonataadmin/vendor/iCheck/skins/square/blue.css
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css
            - bundles/sonataadmin/vendor/jqueryui/themes/base/jquery-ui.css
            - bundles/sonatacore/vendor/select2/select2.css
            - bundles/sonatacore/vendor/select2-bootstrap-css/select2-bootstrap.min.css
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css
            - bundles/sonataadmin/css/styles.css
            - bundles/sonataadmin/css/layout.css
            - bundles/sonataadmin/css/tree.css
            - static/assets/css/custom_admin.css
    templates:
        user_block:           'SonataUserBundle:Admin:Core/user_block.html.twig'
        add_block:            'SonataAdminBundle:Core:add_block.html.twig'
        layout:               'SiteBundle::standard_layout.html.twig'
        ajax:                 'SonataAdminBundle::ajax_layout.html.twig'
        dashboard:            'SonataAdminBundle:Core:dashboard.html.twig'
        search:               'SonataAdminBundle:Core:search.html.twig'
        list:                 'SonataAdminBundle:CRUD:list.html.twig'
        filter:               'SonataAdminBundle:Form:filter_admin_fields.html.twig'
        show:                 'SonataAdminBundle:CRUD:show.html.twig'
        show_compare:         'SonataAdminBundle:CRUD:show_compare.html.twig'
        edit:                 'SiteBundle::edit.html.twig'
        preview:              'SonataAdminBundle:CRUD:preview.html.twig'
        history:              'SonataAdminBundle:CRUD:history.html.twig'
        acl:                  'SonataAdminBundle:CRUD:acl.html.twig'
        history_revision_timestamp:  'SonataAdminBundle:CRUD:history_revision_timestamp.html.twig'
        action:               'SonataAdminBundle:CRUD:action.html.twig'
        select:               'SonataAdminBundle:CRUD:list__select.html.twig'
        list_block:           'SonataAdminBundle:Block:block_admin_list.html.twig'
        search_result_block:  'SonataAdminBundle:Block:block_search_result.html.twig'
        short_object_description:  'SonataAdminBundle:Helper:short-object-description.html.twig'
        delete:               'SonataAdminBundle:CRUD:delete.html.twig'
        batch:                'SonataAdminBundle:CRUD:list__batch.html.twig'
        batch_confirmation:   'SonataAdminBundle:CRUD:batch_confirmation.html.twig'
        inner_list_row:       'SonataAdminBundle:CRUD:list_inner_row.html.twig'
        outer_list_rows_mosaic:  'SonataAdminBundle:CRUD:list_outer_rows_mosaic.html.twig'
        outer_list_rows_list:  'SonataAdminBundle:CRUD:list_outer_rows_list.html.twig'
        outer_list_rows_tree:  'SonataAdminBundle:CRUD:list_outer_rows_tree.html.twig'
        base_list_field:      'SiteBundle::base_list_field.html.twig'
        pager_links:          'SonataAdminBundle:Pager:links.html.twig'
        pager_results:        'SonataAdminBundle:Pager:results.html.twig'
        tab_menu_template:    'SonataAdminBundle:Core:tab_menu_template.html.twig'
        knp_menu_template:    'SonataAdminBundle:Menu:sonata_menu.html.twig'


sonata_doctrine_orm_admin:
    templates:
        form:
            - SiteBundle::form_admin_fields.html.twig


vich_uploader:
   db_driver: orm

   mappings:
       upload:
           uri_prefix:         /upload
           upload_destination: %kernel.root_dir%/../web/upload
           inject_on_load:     true
           delete_on_update:   true
           delete_on_remove:   true
           namer: vich_uploader.namer_uniqid

jms_serializer:
    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"

stfalcon_tinymce:
        selector: ".tinymce"
        language: %locale%

        # Custom buttons
        theme:
            # Simple theme: same as default theme
            simple:
#                 plugins: ["code, link, preview, image"]
#                 toolbar1: "insertfile, bold,italic,underline,undo,redo,link,unlink,removeformat,cleanup,code,preview"
                 plugins:
                     - "code advlist autolink lists link image imageupload charmap print preview hr anchor pagebreak"
                     - "searchreplace wordcount visualblocks visualchars code fullscreen"
                     - "insertdatetime media nonbreaking save table contextmenu directionality"
                     - "emoticons template paste textcolor"
                 toolbar1: "insertfile image imageupload undo redo | styleselect | removeformat | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link"
                 toolbar2: "print preview code media | forecolor backcolor emoticons | stfalcon | example"
                 menubar: false
                 relative_urls: false
                 force_p_newlines: false
                 forced_root_block: false
                 extended_valid_elements: "i[class],a[href|target]"

stof_doctrine_extensions:
   default_locale: en
   translation_fallback: true
   orm:
       default:
           tree: true
           timestampable: true
           sluggable: true

fos_user:
   db_driver:              orm # Required
   firewall_name:          main # Required
   user_class:     SiteBundle\Entity\User


   group:
       group_class:   SiteBundle\Entity\UserGroup
       group_manager: sonata.user.orm.group_manager                    # If you're using doctrine orm (use sonata.user.mongodb.group_manager for mongodb)

   service:
       user_manager: sonata.user.orm.user_manager                      # If you're using doctrine orm (use sonata.user.mongodb.user_manager for mongodb)

   use_listener:           true
   use_username_form_type: true
   model_manager_name:     null  # change it to the name of your entity/document manager if you don't want to use the default one.
   from_email:
       address:        webmaster@example.com
       sender_name:    webmaster
   profile:
       form:
           type:               fos_user_profile # or 'fos_user_profile' on Symfony < 2.8
           name:               fos_user_profile_form
           validation_groups:  [Profile, Default]
   change_password:
       form:
           type:               fos_user_change_password # or 'fos_user_change_password' on Symfony < 2.8
           name:               fos_user_change_password_form
           validation_groups:  [ChangePassword, Default]
   registration:
       confirmation:
           from_email: # Use this node only if you don't want the global email address for the confirmation email
               address:        ...
               sender_name:    ...
           enabled:    false # change to true for required email confirmation
           template:   FOSUserBundle:Registration:email.txt.twig
       form:
           type:               fos_user_registration # or 'fos_user_registration' on Symfony < 2.8
           name:               fos_user_registration_form
           validation_groups:  [Registration, Default]
   resetting:
       token_ttl: 86400
       email:
           from_email: # Use this node only if you don't want the global email address for the resetting email
               address:        ...
               sender_name:    ...
           template:   FOSUserBundle:Resetting:email.txt.twig
       form:
           type:               fos_user_resetting # or 'fos_user_resetting' on Symfony < 2.8
           name:               fos_user_resetting_form
           validation_groups:  [ResetPassword, Default]
   service:
       mailer:                 fos_user.mailer.default
       email_canonicalizer:    fos_user.util.canonicalizer.default
       username_canonicalizer: fos_user.util.canonicalizer.default
       token_generator:        fos_user.util.token_generator.default
       user_manager:           fos_user.user_manager.default


sonata_admin:
    security:
        handler: sonata.admin.security.handler.role

sonata_user:
    class:
        user: SiteBundle\Entity\User
        group: SiteBundle\Entity\UserGroup


white_october_breadcrumbs:
    separator:          ''
    separatorClass:     'separator'
    listId:             'wo-breadcrumbs'
    listClass:          'breadcrumb'
    itemClass:          'active'
    linkRel:            ''
    locale:             ~ # defaults to null, so the default locale is used
    translation_domain: ~ # defaults to null, so the default domain is used
    viewTemplate:       'SiteBundle::breadcrumb.html.twig'

genemu_form:
    captcha:
        width: 200
        height: 50
        font_size: 22

mremi_contact:
    store_data:        true
    contact_class:     SiteBundle\Entity\FeedbackResult
    email:

        from:
            - { address: charlysais@gmail.com, name: "Azaza" }

        to:
            - { address: charlysais@gmail.com, name: "Webmaster" }
        template:
            SiteBundle::email_feedback.txt.twig
    form:
        captcha_type: genemu_captcha
        type: feedback_form


knp_paginator:
    page_range: 1                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig     # sliding pagination controls template
